# Generated by Django 2.0.1 on 2018-11-30 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20181121_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assettype',
            old_name='specs',
            new_name='has_specs',
        ),
    ]
