# Generated by Django 2.0.1 on 2018-05-09 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_condition', models.CharField(choices=[('Brand New', 'Brand New'), ('Working', 'Working'), ('Issues', 'Issues'), ('Not Working', 'Not Working')], max_length=50)),
                ('previous_condition', models.CharField(blank=True, choices=[('Brand New', 'Brand New'), ('Working', 'Working'), ('Issues', 'Issues'), ('Not Working', 'Not Working')], editable=False, max_length=50, null=True)),
                ('condition_description', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Asset Condition',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='current_condition',
            field=models.CharField(default='Brand New', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='assetcondition',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Asset', to_field='serial_number'),
        ),
    ]
