# Generated by Django 2.0.1 on 2018-05-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180509_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcondition',
            name='current_condition',
            field=models.CharField(choices=[('Brand New', 'Brand New'), ('Working', 'Working'), ('Issues', 'Issues'), ('Not Working', 'Not Working')], default='Brand New', max_length=50),
        ),
    ]
