# Generated by Django 2.0.1 on 2018-05-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_assetincidentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetincidentreport',
            name='incident_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='assetincidentreport',
            name='injuries_sustained',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='assetincidentreport',
            name='loss_of_property',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetincidentreport',
            name='police_abstract_obtained',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='assetincidentreport',
            name='witnesses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
