# Generated by Django 2.0.1 on 2018-05-10 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180510_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetcondition',
            name='asset',
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.AssetCondition'),
        ),
    ]
