# Generated by Django 2.0.1 on 2018-05-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180510_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcondition',
            name='condition_description',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
