# Generated by Django 2.0.1 on 2018-07-03 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180529_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocationhistory',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Allocation History'},
        ),
        migrations.AlterModelOptions(
            name='apiuser',
            options={'ordering': ['-id'], 'verbose_name': 'API User'},
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Asset Categories'},
        ),
        migrations.AlterModelOptions(
            name='assetcondition',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Asset Condition'},
        ),
        migrations.AlterModelOptions(
            name='assetincidentreport',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='assetlog',
            options={'ordering': ['-id'], 'verbose_name': 'Asset Log'},
        ),
        migrations.AlterModelOptions(
            name='assetmake',
            options={'ordering': ['-id'], 'verbose_name': 'Asset Make'},
        ),
        migrations.AlterModelOptions(
            name='assetmodelnumber',
            options={'ordering': ['-id'], 'verbose_name': 'Asset Model Number'},
        ),
        migrations.AlterModelOptions(
            name='assetstatus',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Asset Statuses'},
        ),
        migrations.AlterModelOptions(
            name='assetsubcategory',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Asset SubCategories'},
        ),
        migrations.AlterModelOptions(
            name='assettype',
            options={'ordering': ['-id'], 'verbose_name': 'Asset Type'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id'], 'verbose_name_plural': 'All Users'},
        ),
        migrations.AlterModelOptions(
            name='userfeedback',
            options={'ordering': ['-id'], 'verbose_name_plural': 'User Feedback'},
        ),
        migrations.AlterField(
            model_name='allocationhistory',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Asset'),
        ),
        migrations.AlterField(
            model_name='assetcondition',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Asset'),
        ),
        migrations.AlterField(
            model_name='assetincidentreport',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Asset'),
        ),
        migrations.AlterField(
            model_name='assetlog',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Asset'),
        ),
        migrations.AlterField(
            model_name='assetstatus',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Asset'),
        ),
    ]
