# Generated by Django 2.0.1 on 2018-05-11 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180510_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcondition',
            name='asset',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.PROTECT, to='core.Asset', to_field='serial_number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_condition',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
