# Generated by Django 2.0.1 on 2018-05-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180511_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='current_condition',
            field=models.CharField(default='NA', editable=False, max_length=50),
        ),
    ]
