# Generated by Django 2.0.1 on 2018-07-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180703_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
