# Generated by Django 2.0.1 on 2018-07-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180703_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcategory',
            name='category_name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='assetmake',
            name='make_label',
            field=models.CharField(
                max_length=40, unique=True, verbose_name='Asset Make'),
        ),
        migrations.AlterField(
            model_name='assetmodelnumber',
            name='model_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='assetsubcategory',
            name='sub_category_name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='asset_type',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
