# Generated by Django 2.0.1 on 2018-07-09 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180705_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSpecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_manufacture', models.IntegerField(choices=[(2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], null=True, blank=True)),
                ('processor_type', models.CharField(choices=[('Intel core i3', 'Intel core i3'), ('Intel core i5', 'Intel core i5'), ('Intel core i7', 'Intel core i7')], max_length=300, null=True, blank=True)),
                ('processor_speed', models.FloatField(choices=[(1.8, '1.8GHz'), (2.3, '2.3GHz'), (3.0, '3.0GHz'), (3.4, '3.4GHz')], null=True, blank=True)),
                ('screen_size', models.IntegerField(choices=[(13, '13"'), (15, '15"'), (17, '17"')], null=True, blank=True)),
                ('storage', models.IntegerField(choices=[(128, '128GB'), (256, '256GB'), (512, '512GB')], null=True, blank=True)),
                ('memory', models.IntegerField(choices=[(4, '4GB'), (8, '8GB'), (16, '16GB'), (32, '32GB')], null=True, blank=True)),
            ],
            options={
                'verbose_name': 'Asset Specification',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='specs',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.AssetSpecs'),
        ),
    ]
