# Generated by Django 2.0.1 on 2018-05-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180511_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='condition_description',
            field=models.CharField(default='NONE', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_condition',
            field=models.CharField(default='NONE', editable=False, max_length=50),
        ),
    ]
