# Generated by Django 2.0.1 on 2018-05-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180511_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='current_condition',
        ),
        migrations.RemoveField(
            model_name='assetcondition',
            name='current_condition',
        ),
        migrations.RemoveField(
            model_name='assetcondition',
            name='previous_condition',
        ),
    ]
