# Generated by Django 2.0.1 on 2018-07-09 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180709_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='specs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.AssetSpecs'),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='asset_sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.AssetSubCategory'),
        ),
    ]
