# Generated by Django 2.0.1 on 2018-07-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180709_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(default='2018-07-10'),
            preserve_default=False,
        ),
    ]
