# Generated by Django 2.0.1 on 2018-05-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180511_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='condition_description',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
