# Generated by Django 2.0.1 on 2018-07-13 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_asset_purchase_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assetspecs',
            unique_together={('storage', 'memory', 'screen_size', 'processor_speed', 'year_of_manufacture', 'processor_type')},
        ),
    ]
