# Generated by Django 2.0.1 on 2018-05-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180511_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='condition_description',
            field=models.CharField(default='Brand New', editable=False, max_length=50),
        ),
    ]
