# Generated by Django 2.0.1 on 2018-05-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180511_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='condition_description',
            new_name='asset_condition',
        ),
        migrations.RenameField(
            model_name='assetcondition',
            old_name='condition_description',
            new_name='asset_condition',
        ),
    ]
