# Generated by Django 2.0.1 on 2018-07-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_assetincidentreport_submitted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeBlock',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Office Block',
            },
        ),
    ]
