# Generated by Django 2.0.1 on 2018-07-24 09:51

import core.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_officeblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(
                blank=True,
                null=True, validators=[core.validator.validate_date]),
        ),
    ]
