# Generated by Django 2.0.1 on 2018-07-27 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180724_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='model_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.AssetModelNumber'),
        ),
        migrations.AlterField(
            model_name='assetmodelnumber',
            name='make_label',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.AssetMake', verbose_name='Asset Make'),
            preserve_default=False,
        ),
    ]
