# Generated by Django 2.0.1 on 2018-07-24 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180724_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorSection',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.CharField(
                    max_length=100, unique=True)),
                ('office_block', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to='core.OfficeBlock')),
            ],
            options={
                'verbose_name_plural': 'Floor section',
                'ordering': ['-id'],
            },
        ),
    ]
