# Generated by Django 2.0.1 on 2018-08-02 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180726_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeFloorSection',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('floor', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to='core.OfficeFloor')),
            ],
            options={
                'verbose_name': 'Office Floor Section',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='officefloorsection',
            unique_together={('floor', 'name')},
        ),
    ]
