# Generated by Django 2.0.1 on 2018-07-29 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180726_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100, unique=True)),
                ('floor_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.OfficeFloor')),
            ],
            options={
                'verbose_name_plural': 'Floor Sections',
                'ordering': ['-id'],
            },
        ),
    ]
