# Generated by Django 2.0.1 on 2018-08-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20180802_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
