# Generated by Django 2.0.1 on 2018-08-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180727_2320'),
        ('core', '0019_asset_verified'),
    ]

    operations = [
    ]
