# Generated by Django 2.0.1 on 2018-08-07 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0020_auto_20180806_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
            },
        ),
        migrations.RemoveField(
            model_name='allocationhistory',
            name='current_owner',
        ),
        migrations.RemoveField(
            model_name='allocationhistory',
            name='previous_owner',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='allocationhistory',
            name='content',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='allocationhistory',
            name='content_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='allocationhistory',
            name='object',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allocationhistory',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='content_type',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='asset',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
