# Generated by Django 2.0.1 on 2018-08-10 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'populate_assetassignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationhistory',
            name='current_owner',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='current_owner_asset', to='core.AssetAssignee'),
        ),
        migrations.AlterField(
            model_name='allocationhistory',
            name='previous_owner',
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='previous_owner_asset', to='core.AssetAssignee'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assigned_to',
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='core.AssetAssignee'),
        ),
    ]
