# Generated by Django 2.0.1 on 2018-08-10 11:56

from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations, models
import django.db.models.deletion


User = get_user_model()

def populate_asset_assignee(apps, schema_editor):
    for user in User.objects.all():
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAssignee',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.OneToOneField(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    to='core.Department')),
                ('user', models.OneToOneField(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='allocationhistory',
            name='current_owner',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='current_owner_asset', to='core.AssetAssignee'),
        ),
        migrations.AlterField(
            model_name='allocationhistory',
            name='previous_owner',
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='previous_owner_asset', to='core.AssetAssignee'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assigned_to',
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='core.AssetAssignee'),
        ),
        migrations.RunPython(populate_asset_assignee),
    ]
