# Generated by Django 2.0.1 on 2018-08-15 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20180810_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetassignee',
            name='workspace',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.OfficeWorkspace'),
        ),
    ]
