# Generated by Django 2.0.1 on 2018-08-24 12:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20180810_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
