# Generated by Django 2.0.1 on 2018-08-08 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20180808_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='notes',
        ),
    ]
