# Generated by Django 2.0.1 on 2018-08-31 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20180824_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetassignee',
            options={'ordering': ['-id']},
        ),
    ]
