# Generated by Django 2.0.1 on 2018-09-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20180831_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='report_type',
            field=models.CharField(choices=[('feedback', 'feedback'), ('bug', 'bug'), ('feature_request', 'feature request')], max_length=20),
        ),
    ]
