# Generated by Django 2.1.2 on 2018-10-05 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_andelacentre'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_location',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.PROTECT, to='core.AndelaCentre'),
        ),
    ]
