# Generated by Django 2.0.1 on 2018-10-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_andelacentre'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='Kenya', max_length=15),
        ),
    ]
