# Generated by Django 2.1.2 on 2018-11-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_set_default_location_of_assets'),
        ('core', 'populate_andelacenter'),
    ]

    operations = [
    ]
