# Generated by Django 2.0.1 on 2018-11-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_merge_20181102_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='specs',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='andelacentre',
            name='country',
            field=models.CharField(choices=[('Kenya', 'Kenya'), ('Nigeria', 'Nigeria'), ('Rwanda', 'Rwanda'), ('Uganda', 'Uganda')], max_length=25),
        ),
    ]
