# Generated by Django 2.1.2 on 2019-01-02 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20181205_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISUserSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('new_records', models.IntegerField(blank=True, null=True)),
                ('running', models.BooleanField(default=False)),
                ('running_time', models.DurationField(blank=True, null=True)),
                ('successful', models.BooleanField(blank=True, null=True)),
                ('updated_records', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AIS User Sync',
                'verbose_name_plural': 'AIS User Sync',
            },
        ),
        migrations.AlterField(
            model_name='andelacentre',
            name='country',
            field=models.CharField(choices=[('Egypt', 'Egypt'), ('Ghana', 'Ghana'), ('Kenya', 'Kenya'), ('Nigeria', 'Nigeria'), ('Rwanda', 'Rwanda'), ('Uganda', 'Uganda'), ('USA', 'USA')], max_length=25),
        ),
        migrations.AlterField(
            model_name='assetspecs',
            name='year_of_manufacture',
            field=models.IntegerField(blank=True, choices=[(2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.AndelaCentre'),
        ),
    ]
