# Generated by Django 2.1.2 on 2018-12-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20181205_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISUserSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_records', models.IntegerField(blank=True, null=True)),
                ('updated_records', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('running_time', models.DurationField(blank=True, null=True)),
                ('successful', models.BooleanField(blank=True, null=True)),
                ('running', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'AIS User Sync',
                'verbose_name_plural': 'AIS User Sync',
            },
        ),
        migrations.AlterField(
            model_name='andelacentre',
            name='country',
            field=models.CharField(choices=[('Egypt', 'Egypt'), ('Ghana', 'Ghana'), ('Kenya', 'Kenya'), ('Nigeria', 'Nigeria'), ('Rwanda', 'Rwanda'), ('Uganda', 'Uganda'), ('USA', 'USA')], max_length=25),
        ),
    ]
