# Generated by Django 2.1.2 on 2019-01-03 14:09

from django.db import migrations, models
import django.db.models.deletion


def populate_countries(apps, schema_editor):
    location = apps.get_model('core', 'AndelaCentre')
    country = apps.get_model('core', 'Country')
    for centre in location.objects.all():
        updated_country, _ = country.objects.get_or_create(name=centre.country_old)
        centre.country = updated_country
        centre.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20190103_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='andelacentre',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Country'),
        ),
        migrations.RunPython(populate_countries),
    ]
