# Generated by Django 2.1.7 on 2019-03-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20190110_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetincidentreport',
            name='state_transitions',
            field=models.CharField(choices=[('Newly reported', 'Newly reported'), ('Internel assessment', 'Internal assessment'), ('Requires repair', 'Requires repair'), ('Requires external assessment', 'Requires external assessment'), ('Damaged', 'Dameged'), ('Lost', 'Lost'), ('External assessment', 'External assessment')], default='Newly reported', max_length=50),
        ),
    ]
