# Generated by Django 2.1.7 on 2019-03-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0038_auto_20190110_2008")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="slack_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        )
    ]
