# Generated by Django 2.1.5 on 2019-01-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20190110_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
