# Generated by Django 2.1.5 on 2019-02-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_securityuser_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityuser',
            name='active',
        ),
    ]
