# Generated by Django 2.1.7 on 2019-03-20 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_user_slack_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statetransitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transitions', models.CharField(default='Newly reported', max_length=50)),
                ('asset_incident_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.AssetIncidentReport')),
            ],
            options={
                'verbose_name_plural': 'State Transitions',
            },
        ),
    ]
