# Generated by Django 2.1.7 on 2019-03-21 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_statetransitions'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateTransition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Internel assessment', 'Internal assessment'), ('Requires repair', 'Requires repair'), ('Requires external assessment', 'Requires external assessment'), ('Damaged', 'Damaged'), ('Lost', 'Lost')], default='Newly reported', max_length=50)),
                ('asset_incident_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.AssetIncidentReport')),
            ],
            options={
                'verbose_name_plural': 'State Transitions',
            },
        ),
        migrations.RemoveField(
            model_name='statetransitions',
            name='asset_incident_report',
        ),
        migrations.DeleteModel(
            name='Statetransitions',
        ),
    ]
