# Generated by Django 2.1.7 on 2019-04-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_statetransition'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['current_status', 'verified'], name='core_asset_current_94f045_idx'),
        ),
    ]
