# Generated by Django 2.1.7 on 2019-04-22 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20190401_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slack_handle',
        ),
        migrations.AddField(
            model_name='user',
            name='is_securityuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assetcondition',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='assetlog',
            name='checked_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
