# Generated by Django 2.1.7 on 2019-03-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20190321_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statetransition',
            name='state',
            field=models.CharField(default='Newly reported', max_length=50),
        ),
    ]
