# Generated by Django 2.1.7 on 2019-03-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20190321_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetincidentreport',
            name='state',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
