# Generated by Django 2.1.7 on 2019-04-24 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('oauth2_provider', '0005_auto_20170514_1141'),
        ('core', '0042_auto_20190422_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityuser',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='SecurityUser',
        ),
    ]
