# Generated by Django 2.1.7 on 2019-05-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20190424_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statetransition',
            name='state',
        ),
        migrations.AddField(
            model_name='statetransition',
            name='asset_state_from_report',
            field=models.CharField(choices=[('requires repair', 'requires repair'), ('requires external assessment', 'requires external assessment'), ('Damaged', 'Damaged')], default='requires repair', max_length=50),
        ),
        migrations.AddField(
            model_name='statetransition',
            name='incident_report_state',
            field=models.CharField(choices=[('newly reported', 'newly reported'), ('internal assessment', 'internal assessment'), ('external assessment', 'external assessment'), ('out for repair', 'out for repair')], default='newly reported', max_length=50),
        ),
    ]
