# Generated by Django 2.1.7 on 2019-05-09 15:49

import core.models.asset
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20190424_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetincidentreport',
            name='police_abstract',
            field=models.FileField(blank=True, upload_to=core.models.asset.user_abstract, verbose_name='Police Abstract'),
        ),
    ]
