# Generated by Django 2.1.7 on 2019-06-06 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20190510_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationhistory',
            name='assigner',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_assigner', to=settings.AUTH_USER_MODEL),
        ),
    ]
