# Generated by Django 2.1.7 on 2019-06-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20190510_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='invoice_receipt',
            field=models.FileField(blank=True, null=True, upload_to='invoice_receipts/'),
        ),
    ]
