# Generated by Django 2.1.7 on 2019-06-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_allocationhistory_assigner'),
        ('core', '0045_asset_invoice_receipt'),
    ]

    operations = [
    ]
