# Generated by Django 2.1.7 on 2019-07-05 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20190521_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetincidentreport',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
