# Generated by Django 2.1.7 on 2019-07-01 10:47

import core.models.asset
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20190521_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetincidentreport',
            name='police_abstract',
            field=models.FileField(blank=True, upload_to=core.models.asset.user_abstract, verbose_name='Police Abstract'),
        ),
    ]
