# Generated by Django 2.1.10 on 2019-08-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='threshold',
            field=models.IntegerField(default=0),
        ),
    ]
