# Generated by Django 2.1.2 on 2018-10-15 14:24

from django.db import migrations, models


def update_officeblocks_location(apps, schema_editor):
    office_block = apps.get_model('core', 'OfficeBlock')
    andela_centres = apps.get_model('core', 'AndelaCentre')
    block_location = None
    for office_block in office_block.objects.all():
        # find kenya centre
        centre = andela_centres.objects.filter(country="Kenya").exists()
        if centre:
            block_location = centre
        else:
            andela_centres.objects.create(centre_name="Dojo", country="Kenya")
            block_location = andela_centres.objects.filter(
                country="Kenya").exists()
        office_block.location = block_location
        office_block.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20181015_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeblock',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.RunPython(update_officeblocks_location),
    ]
