# Generated by Django 2.0.1 on 2018-03-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
