# Generated by Django 2.0.1 on 2018-03-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_assetsubcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetsubcategory',
            options={'verbose_name_plural': 'Asset Sub Categories'},
        ),
    ]
