# Generated by Django 2.0.1 on 2018-02-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
