# Generated by Django 2.0.1 on 2018-02-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180228_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettype',
            name='asset_type',
            field=models.CharField(max_length=50),
        ),
    ]
