# Generated by Django 2.0.1 on 2018-03-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_assetsubcategory'),
        ('api', '0004_auto_20180228_0827'),
    ]

    operations = [
    ]
