# Generated by Django 2.0.1 on 2018-03-01 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20180301_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='asset_sub_category',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to='api.AssetSubCategory'),
            preserve_default=False,
        ),
    ]
