# Generated by Django 2.0.1 on 2018-03-01 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180301_1412'),
        ('api', '0006_assettype_asset_sub_category'),
    ]

    operations = [
    ]
