# Generated by Django 2.0.1 on 2018-03-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20180301_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModelNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='assetsubcategory',
            options={'verbose_name_plural': 'Asset SubCategories'},
        ),
    ]
