# Generated by Django 2.0.1 on 2018-03-20 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180319_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user',
            new_name='user_id',
        ),
    ]
