# Generated by Django 2.0.1 on 2018-03-05 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180301_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='model_number',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='api.ItemModelNumber'),
        ),
    ]
