# Generated by Django 2.0.1 on 2018-03-05 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180301_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmake',
            name='asset_type',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to='api.AssetType'),
            preserve_default=False,
        ),
    ]
