# Generated by Django 2.0.1 on 2018-03-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_assetsubcategory_asset_category'),
        ('api', '0009_assetmake_asset_type'),
    ]

    operations = [
    ]
