# Generated by Django 2.0.1 on 2018-03-21 08:07

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180320_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityUser',
            fields=[
                ('user_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to=settings.AUTH_USER_MODEL)),
                ('badge_number',
                 models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Security User',
            },
            bases=('api.user',),
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
    ]
