# Generated by Django 2.0.1 on 2018-03-05 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_item_model_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='model_number',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT,
                to='api.ItemModelNumber'),
        ),
    ]
