# Generated by Django 2.0.1 on 2018-03-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_assetmake_asset_type'),
        ('api', '0010_auto_20180305_1252'),
    ]

    operations = [
    ]
