# Generated by Django 2.0.1 on 2018-03-07 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20180306_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodelnumber',
            name='make_label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.AssetMake'),
        ),
    ]
