# Generated by Django 2.0.1 on 2018-04-09 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0011_auto_20180322_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id',
                 models.AutoField(auto_created=True, primary_key=True,
                                  serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to='api.Item')),
                ('security_user', models.ForeignKey(
                    blank=True, default=1,
                    on_delete=django.db.models.deletion.PROTECT,
                    to='api.SecurityUser')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to='api.Item')),
                ('security_user', models.ForeignKey(
                    blank=True,
                    default=1, on_delete=django.db.models.deletion.PROTECT,
                    to='api.SecurityUser')),
            ],
        ),
    ]
