# Generated by Django 2.0.1 on 2018-03-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20180305_1606'),
        ('api', '0011_itemmodelnumber_make_label'),
    ]

    operations = [
    ]
