# Generated by Django 2.0.1 on 2018-04-12 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180322_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('Checkin', 'Checkin'), ('Checkout', 'Checkout')], default='Checkin', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.SecurityUser')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='assetlog',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Item'),
        ),
    ]
