# Generated by Django 2.0.1 on 2018-04-10 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0012_checkincheckout'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLog',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('log_type',
                 models.CharField(
                     choices=[
                         ('Checkin', 'Checkin'), ('Checkout', 'Checkout')
                     ],
                     default='Checkin',
                     max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(
                    blank=True, default=1,
                    on_delete=django.db.models.deletion.PROTECT,
                    to='api.SecurityUser')),
                ('item', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to='api.Item')),
            ],
        ),
        migrations.RemoveField(
            model_name='checkincheckout',
            name='item',
        ),
        migrations.RemoveField(
            model_name='checkincheckout',
            name='security_user',
        ),
        migrations.DeleteModel(
            name='CheckinCheckout',
        ),
    ]
