# Generated by Django 2.0.1 on 2018-03-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20180307_1528'),
        ('api', '0012_merge_20180307_1530'),
    ]

    operations = [
    ]
