# Generated by Django 2.0.1 on 2018-04-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180411_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiuser',
            options={'verbose_name': 'API User'},
        ),
    ]
