# Generated by Django 2.0.1 on 2018-04-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180412_1447'),
        ('api', '0015_auto_20180411_1340'),
    ]

    operations = [
    ]
