# Generated by Django 2.0.1 on 2018-04-13 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0016_merge_20180412_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetlog',
            name='item',
        ),
        migrations.AddField(
            model_name='assetlog',
            name='asset',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to='api.Item', to_field='serial_number'),
            preserve_default=False,
        ),
    ]
