# Generated by Django 2.0.1 on 2018-04-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180413_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_by', models.EmailField(max_length=50, unique=True)),
                ('message', models.CharField(max_length=100, unique=True)),
                ('report_type', models.CharField(choices=[('feedback', 'feedback'), ('bug', 'bug')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
