# Generated by Django 2.0.1 on 2018-04-16 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180413_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='status',
            new_name='allocation_status',
        ),
    ]
