# Generated by Django 2.0.1 on 2018-04-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_userfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='message',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='reported_by',
            field=models.EmailField(max_length=50),
        ),
    ]
