# Generated by Django 2.0.1 on 2018-04-18 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_userfeedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Asset',
        ),
    ]
