# Generated by Django 2.0.1 on 2018-04-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20180418_1025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemModelNumber',
            new_name='AssetModelNumber',
        ),
    ]
