# Generated by Django 2.0.1 on 2018-04-18 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20180418_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='item_code',
            new_name='asset_code',
        ),
    ]
