# Generated by Django 2.0.1 on 2018-04-25 08:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20180418_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('Available', 'Available'), ('Allocated', 'Allocated'), ('Lost', 'Lost'), ('Damaged', 'Damaged')], max_length=50)),
                ('previous_status', models.CharField(blank=True, choices=[('Available', 'Available'), ('Allocated', 'Allocated'), ('Lost', 'Lost'), ('Damaged', 'Damaged')], editable=False, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='asset',
            name='allocation_status',
        ),
        migrations.AddField(
            model_name='asset',
            name='current_status',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetstatus',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Asset', to_field='serial_number'),
        ),
    ]
