# Generated by Django 2.0.1 on 2018-04-25 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20180425_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodelnumber',
            name='make_label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.AssetMake', verbose_name='Asset Make'),
        ),
    ]
