# Generated by Django 2.0.1 on 2018-04-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20180425_0842'),
        ('api', '0027_auto_20180425_0859'),
    ]

    operations = [
    ]
