# Generated by Django 2.0.1 on 2018-04-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_merge_20180425_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetstatus',
            options={'verbose_name_plural': 'Asset Statuses'},
        ),
        migrations.AlterModelOptions(
            name='userfeedback',
            options={'verbose_name_plural': 'User Feedback'},
        ),
    ]
