# Generated by Django 2.0.1 on 2018-04-30 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20180426_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Allocation Histories',
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='assigned_to',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allocationhistory',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Asset', to_field='serial_number'),
        ),
        migrations.AddField(
            model_name='allocationhistory',
            name='current_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_owner_asset', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allocationhistory',
            name='previous_owner',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_owner_asset', to=settings.AUTH_USER_MODEL),
        ),
    ]
