# Generated by Django 2.0.1 on 2018-04-30 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20180430_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocationhistory',
            options={'verbose_name_plural': 'Allocation History'},
        ),
    ]
