# Generated by Django 2.0.1 on 2018-04-26 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20180426_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_owner', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Asset', to_field='serial_number')),
                ('current_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_owner_asset', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Allocation Histories',
            },
        ),
        migrations.RemoveField(
            model_name='allocationshistory',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='allocationshistory',
            name='current_owner',
        ),
        migrations.RemoveField(
            model_name='allocationshistory',
            name='previous_owner',
        ),
        migrations.DeleteModel(
            name='AllocationsHistory',
        ),
    ]
