# Generated by Django 2.0.1 on 2018-04-27 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20180426_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='current_owner',
            new_name='assigned_to',
        ),
    ]
